In [1]:
# Tratamiento de datos
# -----------------------------------------------------------------------
import numpy as np
import pandas as pd

from ast import literal_eval

In [2]:
df= pd.read_csv('parques.csv', index_col = 0)
df.head()

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,...,Seasonality,Conservation Status,Park Code,State,Acres,Latitude,Longitude,State_0,State_1,State_2
4146,BIBE-1000,Big Bend National Park,Mammal,Artiodactyla,Antilocapridae,Antilocapra americana,Pronghorn,Approved,Present,Native,...,Resident,NaN,BIBE,TX,801163,29.25,-103.25,TX,NaN,NaN
4147,BIBE-1001,Big Bend National Park,Mammal,Artiodactyla,Bovidae,Ammotragus lervia,Barbary Sheep Or Aoudad,Approved,Present,Native,...,Resident,NaN,BIBE,TX,801163,29.25,-103.25,TX,NaN,NaN
4148,BIBE-1002,Big Bend National Park,Mammal,Artiodactyla,Bovidae,Bison bison,American Bison,Approved,Not Present (Historical Report),Native,...,NaN,NaN,BIBE,TX,801163,29.25,-103.25,TX,NaN,NaN
4149,BIBE-1003,Big Bend National Park,Mammal,Artiodactyla,Bovidae,Ovis canadensis,Bighorn Sheep,Approved,Present,Native,...,Resident,Species of Concern,BIBE,TX,801163,29.25,-103.25,TX,NaN,NaN
4150,BIBE-1004,Big Bend National Park,Mammal,Artiodactyla,Cervidae,Cervus canadensis,Elk,Approved,Present,Not Native,...,Resident,NaN,BIBE,TX,801163,29.25,-103.25,TX,NaN,NaN

In [3]:
df['State'].unique()

array(['TX', 'AK', 'CA, NV', 'FL', 'MT', 'AZ', 'WA', 'CA', 'WY, MT, ID'],
      dtype=object)

In [4]:
state = df[df['State'].isin(['CA, NV', 'WY, MT, ID'])]
state.head()

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,...,Seasonality,Conservation Status,Park Code,State,Acres,Latitude,Longitude,State_0,State_1,State_2
26085,DEVA-1000,Death Valley National Park,Mammal,Rodentia,Heteromyidae,Perognathus formosus formosus,None,In Review,NaN,NaN,...,NaN,NaN,DEVA,"CA, NV",4740912,36.24,-116.82,CA,NV,NaN
26086,DEVA-1001,Death Valley National Park,Mammal,Rodentia,Heteromyidae,Perognathus formosus mohavensis,None,In Review,NaN,NaN,...,NaN,NaN,DEVA,"CA, NV",4740912,36.24,-116.82,CA,NV,NaN
26087,DEVA-1002,Death Valley National Park,Mammal,Rodentia,Heteromyidae,Perognathus penicillatus stephensi,None,In Review,NaN,NaN,...,NaN,NaN,DEVA,"CA, NV",4740912,36.24,-116.82,CA,NV,NaN
26088,DEVA-1003,Death Valley National Park,Mammal,Rodentia,Cricetidae,Pitymys nemoralis,None,In Review,NaN,NaN,...,NaN,NaN,DEVA,"CA, NV",4740912,36.24,-116.82,CA,NV,NaN
26089,DEVA-1004,Death Valley National Park,Mammal,NaN,Aplodontidae,Aplodontoids,None,In Review,NaN,NaN,...,NaN,NaN,DEVA,"CA, NV",4740912,36.24,-116.82,CA,NV,NaN

In [46]:
state.shape

(8405, 21)

In [5]:
state['Park Name'].value_counts()

Death Valley National Park    4439
Yellowstone National Park     3966
Name: Park Name, dtype: int64

In [6]:
indexes= state.index

In [7]:
type(state['State'].iloc[0])

str

In [8]:
state['State'].unique()

array(['CA, NV', 'WY, MT, ID'], dtype=object)

In [9]:
def tolist(x):
    if len(x.split(',')) == 2:
        lista = [x.split(',')[0], x.split(',')[1]]
        return lista
    else:
        lista2 = [x.split(',')[0], x.split(',')[1], x.split(',')[2]]
        return lista2

In [10]:
state['State'] = state['State'].apply(tolist)

/tmp/ipykernel_225/186900294.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  state['State'] = state['State'].apply(tolist)

In [11]:
state.head()

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,...,Seasonality,Conservation Status,Park Code,State,Acres,Latitude,Longitude,State_0,State_1,State_2
26085,DEVA-1000,Death Valley National Park,Mammal,Rodentia,Heteromyidae,Perognathus formosus formosus,None,In Review,NaN,NaN,...,NaN,NaN,DEVA,"[CA, NV]",4740912,36.24,-116.82,CA,NV,NaN
26086,DEVA-1001,Death Valley National Park,Mammal,Rodentia,Heteromyidae,Perognathus formosus mohavensis,None,In Review,NaN,NaN,...,NaN,NaN,DEVA,"[CA, NV]",4740912,36.24,-116.82,CA,NV,NaN
26087,DEVA-1002,Death Valley National Park,Mammal,Rodentia,Heteromyidae,Perognathus penicillatus stephensi,None,In Review,NaN,NaN,...,NaN,NaN,DEVA,"[CA, NV]",4740912,36.24,-116.82,CA,NV,NaN
26088,DEVA-1003,Death Valley National Park,Mammal,Rodentia,Cricetidae,Pitymys nemoralis,None,In Review,NaN,NaN,...,NaN,NaN,DEVA,"[CA, NV]",4740912,36.24,-116.82,CA,NV,NaN
26089,DEVA-1004,Death Valley National Park,Mammal,NaN,Aplodontidae,Aplodontoids,None,In Review,NaN,NaN,...,NaN,NaN,DEVA,"[CA, NV]",4740912,36.24,-116.82,CA,NV,NaN

In [13]:
state['State']

26085          [CA,  NV]
26086          [CA,  NV]
26087          [CA,  NV]
26088          [CA,  NV]
26089          [CA,  NV]
               ...
115359    [WY,  MT,  ID]
115360    [WY,  MT,  ID]
115361    [WY,  MT,  ID]
115362    [WY,  MT,  ID]
115363    [WY,  MT,  ID]
Name: State, Length: 8405, dtype: object

In [14]:
state2 = state.explode('State')

In [15]:
state2.head()

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,...,Seasonality,Conservation Status,Park Code,State,Acres,Latitude,Longitude,State_0,State_1,State_2
26085,DEVA-1000,Death Valley National Park,Mammal,Rodentia,Heteromyidae,Perognathus formosus formosus,None,In Review,NaN,NaN,...,NaN,NaN,DEVA,CA,4740912,36.24,-116.82,CA,NV,NaN
26085,DEVA-1000,Death Valley National Park,Mammal,Rodentia,Heteromyidae,Perognathus formosus formosus,None,In Review,NaN,NaN,...,NaN,NaN,DEVA,NV,4740912,36.24,-116.82,CA,NV,NaN
26086,DEVA-1001,Death Valley National Park,Mammal,Rodentia,Heteromyidae,Perognathus formosus mohavensis,None,In Review,NaN,NaN,...,NaN,NaN,DEVA,CA,4740912,36.24,-116.82,CA,NV,NaN
26086,DEVA-1001,Death Valley National Park,Mammal,Rodentia,Heteromyidae,Perognathus formosus mohavensis,None,In Review,NaN,NaN,...,NaN,NaN,DEVA,NV,4740912,36.24,-116.82,CA,NV,NaN
26087,DEVA-1002,Death Valley National Park,Mammal,Rodentia,Heteromyidae,Perognathus penicillatus stephensi,None,In Review,NaN,NaN,...,NaN,NaN,DEVA,CA,4740912,36.24,-116.82,CA,NV,NaN

In [16]:
state2['State'].unique()

array(['CA', ' NV', 'WY', ' MT', ' ID'], dtype=object)

In [17]:
state2.shape

(20776, 21)

In [18]:
dfcopy = df.copy()

In [19]:
dfcopy.drop(list(indexes), axis=0, inplace=True)

In [20]:
dfcopy.head()

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,...,Seasonality,Conservation Status,Park Code,State,Acres,Latitude,Longitude,State_0,State_1,State_2
4146,BIBE-1000,Big Bend National Park,Mammal,Artiodactyla,Antilocapridae,Antilocapra americana,Pronghorn,Approved,Present,Native,...,Resident,NaN,BIBE,TX,801163,29.25,-103.25,TX,NaN,NaN
4147,BIBE-1001,Big Bend National Park,Mammal,Artiodactyla,Bovidae,Ammotragus lervia,Barbary Sheep Or Aoudad,Approved,Present,Native,...,Resident,NaN,BIBE,TX,801163,29.25,-103.25,TX,NaN,NaN
4148,BIBE-1002,Big Bend National Park,Mammal,Artiodactyla,Bovidae,Bison bison,American Bison,Approved,Not Present (Historical Report),Native,...,NaN,NaN,BIBE,TX,801163,29.25,-103.25,TX,NaN,NaN
4149,BIBE-1003,Big Bend National Park,Mammal,Artiodactyla,Bovidae,Ovis canadensis,Bighorn Sheep,Approved,Present,Native,...,Resident,Species of Concern,BIBE,TX,801163,29.25,-103.25,TX,NaN,NaN
4150,BIBE-1004,Big Bend National Park,Mammal,Artiodactyla,Cervidae,Cervus canadensis,Elk,Approved,Present,Not Native,...,Resident,NaN,BIBE,TX,801163,29.25,-103.25,TX,NaN,NaN

In [23]:
state.State

26085          [CA,  NV]
26086          [CA,  NV]
26087          [CA,  NV]
26088          [CA,  NV]
26089          [CA,  NV]
               ...
115359    [WY,  MT,  ID]
115360    [WY,  MT,  ID]
115361    [WY,  MT,  ID]
115362    [WY,  MT,  ID]
115363    [WY,  MT,  ID]
Name: State, Length: 8405, dtype: object

In [24]:
df['State'].unique()

array(['TX', 'AK', 'CA, NV', 'FL', 'MT', 'AZ', 'WA', 'CA', 'WY, MT, ID'],
      dtype=object)

In [21]:
dfcopy['State'].unique()

array(['TX', 'AK', 'FL', 'MT', 'AZ', 'WA', 'CA'], dtype=object)

In [25]:
df_state= pd.concat([dfcopy, state2])
df_state.head()

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,...,Seasonality,Conservation Status,Park Code,State,Acres,Latitude,Longitude,State_0,State_1,State_2
4146,BIBE-1000,Big Bend National Park,Mammal,Artiodactyla,Antilocapridae,Antilocapra americana,Pronghorn,Approved,Present,Native,...,Resident,NaN,BIBE,TX,801163,29.25,-103.25,TX,NaN,NaN
4147,BIBE-1001,Big Bend National Park,Mammal,Artiodactyla,Bovidae,Ammotragus lervia,Barbary Sheep Or Aoudad,Approved,Present,Native,...,Resident,NaN,BIBE,TX,801163,29.25,-103.25,TX,NaN,NaN
4148,BIBE-1002,Big Bend National Park,Mammal,Artiodactyla,Bovidae,Bison bison,American Bison,Approved,Not Present (Historical Report),Native,...,NaN,NaN,BIBE,TX,801163,29.25,-103.25,TX,NaN,NaN
4149,BIBE-1003,Big Bend National Park,Mammal,Artiodactyla,Bovidae,Ovis canadensis,Bighorn Sheep,Approved,Present,Native,...,Resident,Species of Concern,BIBE,TX,801163,29.25,-103.25,TX,NaN,NaN
4150,BIBE-1004,Big Bend National Park,Mammal,Artiodactyla,Cervidae,Cervus canadensis,Elk,Approved,Present,Not Native,...,Resident,NaN,BIBE,TX,801163,29.25,-103.25,TX,NaN,NaN

In [26]:
df_state.shape

(44933, 21)

In [27]:
df_state['State'].value_counts()

AK     10683
CA      6434
 NV     4439
WY      3966
 MT     3966
 ID     3966
AZ      2622
MT      2556
TX      2269
FL      2084
WA      1948
Name: State, dtype: int64

In [28]:
df.columns

Index(['Species ID', 'Park Name', 'Category', 'Order', 'Family',
       'Scientific Name', 'Common Names', 'Record Status', 'Occurrence',
       'Nativeness', 'Abundance', 'Seasonality', 'Conservation Status',
       'Park Code', 'State', 'Acres', 'Latitude', 'Longitude', 'State_0',
       'State_1', 'State_2'],
      dtype='object')

In [29]:
df_state.drop(['State_0', 'State_1', 'State_2'], axis=1, inplace=True)

In [30]:
df_state.columns

Index(['Species ID', 'Park Name', 'Category', 'Order', 'Family',
       'Scientific Name', 'Common Names', 'Record Status', 'Occurrence',
       'Nativeness', 'Abundance', 'Seasonality', 'Conservation Status',
       'Park Code', 'State', 'Acres', 'Latitude', 'Longitude'],
      dtype='object')

In [31]:
df_state["State"] = df_state["State"].apply(lambda x:x.lstrip())
df_state['State'].value_counts()

AK    10683
MT     6522
CA     6434
NV     4439
WY     3966
ID     3966
AZ     2622
TX     2269
FL     2084
WA     1948
Name: State, dtype: int64

In [32]:
df_state.to_csv('parques_bienlimpio.csv')